---
title: "Recipe"
author: "Wenjun Sun"
date: "2020/4/14"
output: 
  html_document:
    df_print: paged
    code_folding: show
    fig_width: 8
    fig_height: 6
---

```{r Setup, include=FALSE, results='hide', warning=FALSE}
library(knitr)
opts_chunk$set(fig.path="figures\\",
               cache.path="cache\\",
               cache=FALSE,
               echo=TRUE,
               message=FALSE,
               warning=FALSE) 
library(dplyr)
library(tidyverse)

library(httr)
library(jsonlite)

#library(tm)
library(wordcloud)
```

# Recipe {.tabset .tabset-fade .tabset-pills}

## Get the data

Extract the Top 1000 popular vegetarian recipes and their ingredient using [Spoonacular API](https://spoonacular.com/food-api). 

```{r eval=FALSE}
# the API key of Spoonacular is stored as environment variable "spoonacular_api_key" and "spoonacular_api_key_ljy"

# store and retrive key to environment 
#Sys.setenv(spoonacular_api_key = "")
#Sys.getenv("spoonacular_api_key")


combined <- data.frame(recipe_id = integer(),
                       recipe_name = character())

for (n in seq(0,900,100)) {
  request <- httr::GET(
    "https://api.spoonacular.com/recipes/complexSearch", 
    query = list(apiKey = Sys.getenv("spoonacular_api_key"),
                 diet = "vegetarian",
                 number = 100,
                 offset = n, # Spoonacular API only allows this to range from 0 to 900
                 sort = "popularity",
                 sortDirection = "desc"
                 )
    )  
  
  response <- jsonlite::fromJSON(httr::content(request, as = "text", encoding = "UTF-8"), flatten = TRUE)[[1]] %>%
  dplyr::select(recipe_id = id, recipe_name = title)
  
  combined <- rbind(combined, response)
  
  print(paste("extracted", n + 100, "recipes"))
}

save(combined, file = "combined_recipe_id.RData")
```

```{r}
combined <- combined %>%
  mutate(ingredient = NA)

for (i in 1:nrow(combined)) {
  recipe_id <- combined[i, "recipe_id"]
  request <- httr::GET(
    paste0("https://api.spoonacular.com/recipes/",recipe_id,"/ingredientWidget.json"), 
    query = list(apiKey = Sys.getenv("spoonacular_api_key")))
  
  response <- jsonlite::fromJSON(httr::content(request, as = "text", encoding = "UTF-8"), flatten = TRUE)[[1]] 
  
  ingredient <- response[["name"]]
  
  combined[i, "ingredient"] <- paste(ingredient, collapse = "//")
}

save(combined, file = "combined_recipe_id_ingredient.RData")
```

## Preprocess

```{r clean ingredient}
library(stringr)
library(SemNetCleaner)

load("combined_recipe_id_ingredient.RData")

allIngredient <- paste(combined$ingredient, collapse = "//")
ingredientList <- strsplit(allIngredient, "//")
ingredientDf <- data.frame(ingredientList, stringsAsFactors = FALSE)
names(ingredientDf) <- "ingredient"

ingredientDf <- ingredientDf %>%
  mutate(ingredient = case_when(ingredient %in% c("bread flour", "all purpose flour","gluten-free gluten free all purpose baking flour","whole wheat white flour","canned all purpose flour","plain flour","AP flour","plain all purpose flour","gluten free flour","gluten-free flour","unbleached flour","unbleached all purpose flour","white bread flour") ~ "flour",
                                ingredient %in% c("whole wheat flour","white whole wheat flour","white whole wheat pastry flour","whole-wheat pastry flour") ~ "whole wheat flour",
                                ingredient == "ground cinnamon" ~ "cinnamon",
                                ingredient == "baking powder" ~ "baking soda",
                                ingredient == "garlic cloves" ~ "garlic",
                                ingredient %in% c("fresh lemon juice", "lemon (juice)") ~ "lemon juice",
                                ingredient == "egg yolks" ~ "egg yolk",
                                ingredient == "egg whites" ~ "egg white",
                                ingredient %in% c("unsalted butter", "salted butter", "unsalted salted butter") ~ "butter",
                                ingredient == "half n half cream" ~ "half & half cream",
                                ingredient %in% c("red onion", "vidalia onion", "yellow onion", "white onion", "sweet onion", "red white yellow onion", "red diced onion", "white yellow onion", "yellow onions", "red onions", "sweet onions", "onions") ~ "onion",
                                ingredient %in% c("green onions", "spring onions", "scallions", "green white scallions", "scallion", "green white light scallions") ~ "green onion",
                                ingredient == "apples" ~ "apple",
                                ingredient == "basil leaves" ~ "basil",
                                ingredient == "bay leaves" ~ "bay leaf",
                                ingredient %in% c("barbecue sauce", "Barbeque Dipping Sauce") ~ "bbq sauce",
                                TRUE ~ ingredient))

ingredientDf[str_detect(ingredientDf$ingredient, "\\b(apple|apples)$"),] <- "apple" # because the singularize() function has trouble dealing with "apples", so we have to move this one up to here

ingredientDf <- ingredientDf %>%
  mutate(ingredient = str_replace(ingredient, "^(dried |diced |fresh |frozen |whole )+(.*)$", "\\2")) # remove leading dried, diced ...

ingredientDf$ingredient <- unlist(map(ingredientDf$ingredient, singularize)) # plural to single, takes a few minutes to run

# combine some too detailed ingredient
ingredientDf[str_detect(ingredientDf$ingredient, "sugar"),]  <- "sugar"
ingredientDf[str_detect(ingredientDf$ingredient, "\\bsalt\\b"),] <- "salt"
ingredientDf[str_detect(ingredientDf$ingredient, "flour tortillas"),] <- "flour tortillas"
ingredientDf[str_detect(ingredientDf$ingredient, "coconut milk"),] <- "coconut milk"
ingredientDf[str_detect(ingredientDf$ingredient, "peanut butter"),] <- "peanut butter"
ingredientDf[str_detect(ingredientDf$ingredient, "oil$"),] <- "oil"
ingredientDf[str_detect(ingredientDf$ingredient, "cheese$"),] <- "cheese"
ingredientDf[str_detect(ingredientDf$ingredient, "sour cream$"),] <- "sour cream"

ingredientDfCleaned <- ingredientDf %>%
  group_by(ingredient) %>%
  summarise(cnt = n()) %>%
  ungroup() %>%
  arrange(desc(cnt))

save(ingredientDfCleaned, file = "ingredientDfCleaned.RData")
```

## Visualization 

### Wordcloud

If all ingredients are included ... 

```{r}
library(wordcloud)

wordcloudDf <- ingredientDfCleaned 

set.seed(1997)
wordcloud(wordcloudDf$ingredient, wordcloudDf$cnt, scale = c(2,.5), min.freq = 0,
          max.words = 100, 
          colors = "#41ab5d")
```

Exclude ingredients that are too rara (appeared less than 5 times) or too common (more than 100 times).  

```{r}
wordcloudDf <- ingredientDfCleaned %>%
  filter(cnt > 10 & cnt < 100) 

set.seed(1997)
wordcloud(wordcloudDf$ingredient, wordcloudDf$cnt, scale = c(1.5,.25), min.freq = 0,
          max.words = 100, 
          colors = brewer.pal(max(7, ncol(wordcloudDf$cnt)),"Greens"))
```

### Bar

### Network


